create table if not exists paper_trade (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    asset varchar(16) not null,
    side varchar(8) not null,
    strategy varchar(100) not null,
    status varchar(16) not null,
    reference_price numeric(24,8) not null,
    invalidation_price numeric(24,8) not null,
    approved_notional_eur numeric(24,2) not null,
    fill_price_eur numeric(24,8),
    fee_eur numeric(24,2) not null,
    signal_strength double precision not null,
    thesis varchar(2000) not null,
    decision_reasons varchar(2000) not null
);

create table if not exists paper_account (
    id bigint primary key,
    cash_eur numeric(24,8) not null,
    start_of_day_equity_eur numeric(24,8) not null,
    start_of_week_equity_eur numeric(24,8) not null,
    high_water_mark_equity_eur numeric(24,8) not null
);

create table if not exists paper_position (
    asset varchar(16) primary key,
    quantity numeric(30,12) not null
);

create index if not exists idx_paper_trade_created_at on paper_trade (created_at desc);
